{% set version = "0.47" %}

package:
  name: olefile
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/olefile/olefile-{{ version }}.zip
  sha256: 599383381a0bf3dfbd932ca0ca6515acd174ed48870cbf7fee123d698c192c1c

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - olefile

about:
  home: http://www.decalage.info/python/olefileio
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: >
    Python package to parse, read and write Microsoft OLE2 files (Structured Storage or Compound Document, Microsoft Office) - Improved version of the OleFileIO module from PIL, the Python Image Library.
  dev_url: https://github.com/decalage2/olefile

extra:
  recipe-maintainers:
    - dgursoy
    - decarlof
    - ericdill
    - licode
    - ravescovi
    - tacaswell
    - ocefpaf
